### ISSUE TITLE
Where are the configuration files?

### ISSUE THREAD

**Issue by alphaDev23** [miclip/nuget-resource#1]
The readme show what appears to be part of a yaml sample configuration but provides no explanation as to where this code goes. Is this one or many configuration files?  Which directory are they copied to in the container?  Did I overlook a file in this repository that provides the configuration file?

**Comment by miclip** [comment]
Hi 

This is a Concourse resource for pulling or pushing nuget packages from a Concourse pipeline. Here's an example https://github.com/miclip/dotnet-resource-test-application, the YAML file is in the `ci` directory.
